# IRIS

In [54]:
# map
# Kfold
# KNN
# SVM
# Bagging (svm)
# Confussion Matrix
# Classification Report

In [55]:
import pandas as pd
import numpy as np

In [56]:
from sklearn.datasets import data

In [57]:
data=pd.read_csv(r"C:\Users\Parimal\Downloads\iris2 (1).csv")

In [58]:
data

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [59]:
data.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [60]:
from sklearn.preprocessing import LabelEncoder

# LabelEncoding (map)

In [61]:
data["Species"].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [62]:
data["Species"]=data["Species"].map({"Iris-setosa":0,"Iris-versicolor":1,"Iris-virginica":2})

In [63]:
data

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0      1            5.1           3.5            1.4           0.2        0
1      2            4.9           3.0            1.4           0.2        0
2      3            4.7           3.2            1.3           0.2        0
3      4            4.6           3.1            1.5           0.2        0
4      5            5.0           3.6            1.4           0.2        0
..   ...            ...           ...            ...           ...      ...
145  146            6.7           3.0            5.2           2.3        2
146  147            6.3           2.5            5.0           1.9        2
147  148            6.5           3.0            5.2           2.0        2
148  149            6.2           3.4            5.4           2.3        2
149  150            5.9           3.0            5.1           1.8        2

[150 rows x 6 columns]

In [64]:
data["Species"].unique()

array([0, 1, 2], dtype=int64)

In [65]:
data["Species"].value_counts()

0    50
1    50
2    50
Name: Species, dtype: int64

In [66]:
x=data.iloc[:,[1,2,3,4]]
x

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0              5.1           3.5            1.4           0.2
1              4.9           3.0            1.4           0.2
2              4.7           3.2            1.3           0.2
3              4.6           3.1            1.5           0.2
4              5.0           3.6            1.4           0.2
..             ...           ...            ...           ...
145            6.7           3.0            5.2           2.3
146            6.3           2.5            5.0           1.9
147            6.5           3.0            5.2           2.0
148            6.2           3.4            5.4           2.3
149            5.9           3.0            5.1           1.8

[150 rows x 4 columns]

In [67]:
y=data.iloc[:,-1]
y

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: Species, Length: 150, dtype: int64

In [68]:
data["Species"].unique()

array([0, 1, 2], dtype=int64)

In [69]:
from sklearn.preprocessing import StandardScaler

In [70]:
sc=StandardScaler()

In [71]:
x=sc.fit_transform(x)

In [72]:
print(x)

[[-9.00681170e-01  1.03205722e+00 -1.34127240e+00 -1.31297673e+00]
 [-1.14301691e+00 -1.24957601e-01 -1.34127240e+00 -1.31297673e+00]
 [-1.38535265e+00  3.37848329e-01 -1.39813811e+00 -1.31297673e+00]
 [-1.50652052e+00  1.06445364e-01 -1.28440670e+00 -1.31297673e+00]
 [-1.02184904e+00  1.26346019e+00 -1.34127240e+00 -1.31297673e+00]
 [-5.37177559e-01  1.95766909e+00 -1.17067529e+00 -1.05003079e+00]
 [-1.50652052e+00  8.00654259e-01 -1.34127240e+00 -1.18150376e+00]
 [-1.02184904e+00  8.00654259e-01 -1.28440670e+00 -1.31297673e+00]
 [-1.74885626e+00 -3.56360566e-01 -1.34127240e+00 -1.31297673e+00]
 [-1.14301691e+00  1.06445364e-01 -1.28440670e+00 -1.44444970e+00]
 [-5.37177559e-01  1.49486315e+00 -1.28440670e+00 -1.31297673e+00]
 [-1.26418478e+00  8.00654259e-01 -1.22754100e+00 -1.31297673e+00]
 [-1.26418478e+00 -1.24957601e-01 -1.34127240e+00 -1.44444970e+00]
 [-1.87002413e+00 -1.24957601e-01 -1.51186952e+00 -1.44444970e+00]
 [-5.25060772e-02  2.18907205e+00 -1.45500381e+00 -1.31297673e

In [73]:
from sklearn.model_selection import KFold

In [74]:
cv=KFold(n_splits=5,random_state=0,shuffle=True)

In [75]:
from sklearn.neighbors import KNeighborsClassifier
model=KNeighborsClassifier()

In [76]:
from sklearn.model_selection import cross_val_score
scores=cross_val_score(model,x,y,cv=cv)

In [77]:
scores

array([1.        , 0.86666667, 1.        , 1.        , 0.9       ])

In [78]:
from numpy import mean

In [79]:
accu_knn=mean(scores)

# Accuracy KNN

In [80]:
accu_knn

0.9533333333333334

In [81]:
from sklearn.svm import SVC

In [82]:
svm=SVC()
svm.fit(x,y)

SVC()

# Accuracy SVM

In [100]:
scores=cross_val_score(svm,x,y,cv=cv)
y_pred_svm=mean(scores)
y_pred_svm

0.9666666666666666

In [101]:
from sklearn.ensemble import BaggingClassifier

In [102]:
bg=BaggingClassifier(base_estimator=svm,n_estimators=10)
bg

BaggingClassifier(base_estimator=SVC())

In [103]:
scores=cross_val_score(bg,x,y,cv=cv)

In [104]:
scores

array([1.        , 0.9       , 1.        , 1.        , 0.96666667])

# Accuracy Bagging

In [105]:
accu_bg=mean(scores)
accu_bg

0.9733333333333333

In [106]:
from sklearn.metrics import confusion_matrix

# Confusion  Matrix

In [114]:
for train_data, test_data in cv.split(x,y):
    x_train,x_test,y_train,y_test=x[train_data], x[test_data],y[train_data],y[test_data]
    bg.fit(x_train,y_train)
    y_pred_bg=bg.predict(x_test)
    print(confusion_matrix(y_pred_bg,y_test))

[[11  0  0]
 [ 0 13  0]
 [ 0  0  6]]
[[ 5  0  0]
 [ 0  9  3]
 [ 0  1 12]]
[[10  0  0]
 [ 0 10  0]
 [ 0  0 10]]
[[14  0  0]
 [ 0  6  0]
 [ 0  0 10]]
[[10  0  0]
 [ 0 10  0]
 [ 0  1  9]]


# Accuracy Report

In [115]:
from sklearn.metrics import classification_report

In [116]:
for train_data, test_data in cv.split(x,y):
    x_train,x_test,y_train,y_test=x[train_data], x[test_data],y[train_data],y[test_data]
    bg.fit(x_train,y_train)
    y_pred_bg=bg.predict(x_test)
    print(classification_report(y_pred_bg,y_test))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00         6

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         5
           1       0.90      0.82      0.86        11
           2       0.87      0.93      0.90        14

    accuracy                           0.90        30
   macro avg       0.92      0.92      0.92        30
weighted avg       0.90      0.90      0.90        30

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00        10
           2       1.00      1.00      1.00        10

    accuracy        